export const GET_ALL_SUBSCRIPTION_PAGE_REQUEST =
  'GET_ALL_SUBSCRIPTION_PAGE_REQUEST';
export const GET_ALL_SUBSCRIPTION_PAGE_SUCCESS =
  'GET_ALL_SUBSCRIPTION_PAGE_SUCCESS';
export const GET_ALL_SUBSCRIPTION_PAGE_FAILED =
  'GET_ALL_SUBSCRIPTION_PAGE_FAILED';

export const SUBMIT_SUBSCRIPTION_PAGE_REQUEST =
  'SUBMIT_SUBSCRIPTION_PAGE_REQUEST';
export const SUBMIT_SUBSCRIPTION_PAGE_SUCCESS =
  'SUBMIT_SUBSCRIPTION_PAGE_SUCCESS';
export const SUBMIT_SUBSCRIPTION_PAGE_FAILED =
  'SUBMIT_SUBSCRIPTION_PAGE_FAILED';

export const RESET_SUBSCRIPTION_SUBMIT = 'RESET_SUBSCRIPTION_SUBMIT';
