export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const RESET_CONTENT = 'RESET_CONTENT';

export const ADD_NEW_REEL = 'ADD_NEW_REEL';

export const GET_REEL_INITIAL_TUTORS_REQUEST =
  'GET_REEL_INITIAL_TUTORS_REQUEST';
export const GET_REEL_INITIAL_TUTORS_SUCCESS =
  'GET_REEL_INITIAL_TUTORS_SUCCESS';
export const GET_REEL_INITIAL_TUTORS_FAILED = 'GET_REEL_INITIAL_TUTORS_FAILED';

export const GET_REEL_MORE_TUTORS_REQUEST = 'GET_REEL_MORE_TUTORS_REQUEST';
export const GET_REEL_MORE_TUTORS_SUCCESS = 'GET_REEL_MORE_TUTORS_SUCCESS';
export const GET_REEL_MORE_TUTORS_FAILED = 'GET_REEL_MORE_TUTORS_FAILED';

export const RESET_TUTOR = 'RESET_TUTOR';

export const GET_REEL_INITIAL_CONTENT_REQUEST =
  'GET_REEL_INITIAL_CONTENT_REQUEST';
export const GET_REEL_INITIAL_CONTENT_SUCCESS =
  'GET_REEL_INITIAL_CONTENT_SUCCESS';
export const GET_REEL_INITIAL_CONTENT_FAILED =
  'GET_REEL_INITIAL_CONTENT_FAILED';

export const SELECT_REEL_TUTOR = 'SELECT_REEL_TUTOR';
export const SET_SELECTED_CONTENT = 'SET_SELECTED_CONTENT';

export const GET_PRODUCT_SUBSCRIPTION_STATS_FAILED =
  'GET_PRODUCT_SUBSCRIPTION_STATS_FAILED';
export const GET_PRODUCT_SUBSCRIPTION_STATS_REQUEST =
  'GET_PRODUCT_SUBSCRIPTION_STATS_REQUEST';
export const GET_PRODUCT_SUBSCRIPTION_STATS_SUCCESS =
  'GET_PRODUCT_SUBSCRIPTION_STATS_SUCCESS';

export const GET_REEL_TUTOR_VIDEO_COUNT_REQUEST =
  'GET_REEL_TUTOR_VIDEO_COUNT_REQUEST';
export const GET_REEL_TUTOR_VIDEO_COUNT_SUCCESS =
  'GET_REEL_TUTOR_VIDEO_COUNT_SUCCESS';
export const GET_REEL_TUTOR_VIDEO_COUNT_FAILED =
  'GET_REEL_TUTOR_VIDEO_COUNT_FAILED';

export const DELETE_REEL = 'DELETE_REEL';
export const SELECT_REEL_ALL_CONTENTS = 'SELECT_REEL_ALL_CONTENTS';

export const SELECT_ALL_CONTENT_BY_CONTENT_TYPE =
  'SELECT_ALL_CONTENT_BY_CONTENT_TYPE';

export const SAVE_REEL = 'SAVE_REEL';
export const EDIT_REEL = 'EDIT_REEL';

export const REEL_MOVE_UP = 'REEL_MOVE_UP';
export const REEL_MOVE_DOWN = 'REEL_MOVE_DOWN';

//---FEATURE REEL

export const EDIT_FEATURE_REEL = 'EDIT_FEATURE_REEL';
export const ADD_NEW_FEATURE_REEL = 'ADD_NEW_FEATURE_REEL';
export const RESET_FEATURE_TUTOR = 'RESET_FEATURE_TUTOR';

export const GET_FEATURE_REEL_INITIAL_TUTORS_REQUEST =
  'GET_FEATURE_REEL_INITIAL_TUTORS_REQUEST';
export const GET_FEATURE_REEL_INITIAL_TUTORS_SUCCESS =
  'GET_FEATURE_REEL_INITIAL_TUTORS_SUCCESS';
export const GET_FEATURE_REEL_INITIAL_TUTORS_FAILED =
  'GET_FEATURE_REEL_INITIAL_TUTORS_FAILED';

export const GET_FEATURE_REEL_MORE_TUTORS_REQUEST =
  'GET_FEATURE_REEL_MORE_TUTORS_REQUEST';
export const GET_FEATURE_REEL_MORE_TUTORS_SUCCESS =
  'GET_FEATURE_REEL_MORE_TUTORS_SUCCESS';
export const GET_FEATURE_REEL_MORE_TUTORS_FAILED =
  'GET_FEATURE_REEL_MORE_TUTORS_FAILED';

export const GET_FEATURE_REEL_INITIAL_CONTENT_REQUEST =
  'GET_FEATURE_REEL_INITIAL_CONTENT_REQUEST';
export const GET_FEATURE_REEL_INITIAL_CONTENT_SUCCESS =
  'GET_FEATURE_REEL_INITIAL_CONTENT_SUCCESS';
export const GET_FEATURE_REEL_INITIAL_CONTENT_FAILED =
  'GET_FEATURE_REEL_INITIAL_CONTENT_FAILED';

export const RESET_FEATURE_CONTENT = 'RESET_FEATURE_CONTENT';

export const GET_FEATURE_REEL_TUTOR_VIDEO_COUNT_REQUEST =
  'GET_FEATURE_REEL_TUTOR_VIDEO_COUNT_REQUEST';
export const GET_FEATURE_REEL_TUTOR_VIDEO_COUNT_SUCCESS =
  'GET_FEATURE_REEL_TUTOR_VIDEO_COUNT_SUCCESS';
export const GET_FEATURE_REEL_TUTOR_VIDEO_COUNT_FAILED =
  'GET_FEATURE_REEL_TUTOR_VIDEO_COUNT_FAILED';

export const SELECT_FEATURE_REEL_TUTOR = 'SELECT_FEATURE_REEL_TUTOR';
export const SET_SELECTED_FEATURE_REEL_CONTENT =
  'SET_SELECTED_FEATURE_REEL_CONTENT';

export const SELECT_FEATURE_REEL_ALL_CONTENTS_REQUEST =
  '  SELECT_FEATURE_REEL_ALL_CONTENTS_REQUEST';
export const SELECT_FEATURE_REEL_ALL_CONTENTS_SUCCESS =
  '      SELECT_FEATURE_REEL_ALL_CONTENTS_SUCCESS';
export const SELECT_FEATURE_REEL_ALL_CONTENTS_FAILED =
  '      SELECT_FEATURE_REEL_ALL_CONTENTS_FAILED';

export const GET_CONTENT_IDS_REQUEST = 'GET_CONTENT_IDS_REQUEST';
export const GET_CONTENT_IDS_SUCCESS = 'GET_CONTENT_IDS_SUCCESS';
export const GET_CONTENT_IDS_FAILED = 'GET_CONTENT_IDS_FAILED';

export const GET_FEATURE_REEL_SELECTED_CONTENT_REQUEST =
  'GET_FEATURE_REEL_SELECTED_CONTENT_REQUEST';
export const GET_FEATURE_REEL_SELECTED_CONTENT_SUCCESS =
  'GET_FEATURE_REEL_SELECTED_CONTENT_SUCCESS';
export const GET_FEATURE_REEL_SELECTED_CONTENT_FAILED =
  'GET_FEATURE_REEL_SELECTED_CONTENT_FAILED';

export const SAVE_FEATURE_REEL = 'SAVE_FEATURE_REEL';

export const RESET_CONTENT_IDS = 'RESET_CONTENT_IDS';

export const SELECT_ALL_FEATURE_REEL_CONTENT_BY_CONTENT_TYPE_REQUEST =
  'SELECT_ALL_FEATURE_REEL_CONTENT_BY_CONTENT_TYPE_REQUEST';
export const SELECT_ALL_FEATURE_REEL_CONTENT_BY_CONTENT_TYPE_SUCCESS =
  'SELECT_ALL_FEATURE_REEL_CONTENT_BY_CONTENT_TYPE_SUCCESS';
export const SELECT_ALL_FEATURE_REEL_CONTENT_BY_CONTENT_TYPE_FAILED =
  'SELECT_ALL_FEATURE_REEL_CONTENT_BY_CONTENT_TYPE_FAILED';

export const GET_REEL_ALL_TUTORS_REQUEST = 'GET_REEL_ALL_TUTORS_REQUEST';
export const GET_REEL_ALL_TUTORS_SUCCESS = 'GET_REEL_ALL_TUTORS_SUCCESS';
export const GET_REEL_ALL_TUTORS_FAILED = 'GET_REEL_ALL_TUTORS_FAILED';
export const UPDATE_DEFAULT_PRODUCT_ACCESS = 'UPDATE_DEFAULT_PRODUCT_ACCESS';
export const UPDATE_ACCESS_CONTROL_USERS_LIST =
  'UPDATE_ACCESS_CONTROL_USERS_LIST';
export const UPDATE_PRODUCT_USER_ACCESS_BULK =
  'UPDATE_PRODUCT_USER_ACCESS_BULK';
export const UPDATE_PRODUCT_USER_SPECIAL_PRICE_BULK =
  'UPDATE_PRODUCT_USER_SPECIAL_PRICE_BULK';

export const UPDATE_TUTOR_BULK = 'UPDATE_TUTOR_BULK';
export const GET_FEATURE_REEL_SELECTED_CONTENT_TUTOR_REQUEST =
  'GET_FEATURE_REEL_SELECTED_CONTENT_TUTOR_REQUEST';
export const GET_FEATURE_REEL_SELECTED_CONTENT_TUTOR_SUCCESS =
  'GET_FEATURE_REEL_SELECTED_CONTENT_TUTOR_SUCCESS';
export const GET_FEATURE_REEL_SELECTED_CONTENT_TUTOR_FAILED =
  'GET_FEATURE_REEL_SELECTED_CONTENT_TUTOR_FAILED';

export const CHANGE_CONTENT_ORDER = 'CHANGE_CONTENT_ORDER';

export const SET_SELECTED_COUNTRIES = 'SET_SELECTED_COUNTRIES';

export const GET_USER_SUBSCRIPTIONS_REQUEST = 'GET_USER_SUBSCRIPTIONS_REQUEST';
export const GET_USER_SUBSCRIPTIONS_SUCCESS = 'GET_USER_SUBSCRIPTIONS_SUCCESS';
export const GET_USER_SUBSCRIPTIONS_FAILED = 'GET_USER_SUBSCRIPTIONS_FAILED';

export const GET_USER_SUBSCRIPTION_DETAILS_REQUEST =
  'GET_USER_SUBSCRIPTION_DETAILS_REQUEST';
export const GET_USER_SUBSCRIPTION_DETAILS_SUCCESS =
  'GET_USER_SUBSCRIPTION_DETAILS_SUCCESS';
export const GET_USER_SUBSCRIPTION_DETAILS_FAILED =
  'GET_USER_SUBSCRIPTION_DETAILS_FAILED';
export const SET_BASIC_INFORMATION = 'SET_BASIC_INFORMATION';

export const ADD_SELECTED_SUBSCRIPTION = 'ADD_SELECTED_SUBSCRIPTION';
export const DELETE_SELECTED_SUBSCRIPTION = 'DELETE_SELECTED_SUBSCRIPTION';
export const UPDATE_PRODUCT_SUBSCRIPTION_DEFAULT_PRICE_BULK =
  'UPDATE_PRODUCT_SUBSCRIPTION_DEFAULT_PRICE_BULK';
export const RESET_CREATE_PRODUCT = 'RESET_CREATE_PRODUCT';

export const UPDATE_FORMATTED_PRODUCT_DATA = 'UPDATE_FORMATTED_PRODUCT_DATA';

export const SAVE_PRODUCT_REQUEST = 'SAVE_PRODUCT_REQUEST';
export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
export const SAVE_PRODUCT_FAILED = 'SAVE_PRODUCT_FAILED';
export const RESET_FEATURE_REEL_SELECTED_CONTENTS =
  'RESET_FEATURE_REEL_SELECTED_CONTENTS';

export const RESET_PRODUCTS = 'RESET_PRODUCTS';
