export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_INITIALIZE = 'LOGIN_INITIALIZE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const UPDATE_ACCESS_TOKEN = 'UPDATE_ACCESS_TOKEN';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const USER_TYPE_REQUEST = 'USER_TYPE_REQUEST';
export const USER_TYPE_SUCCESS = 'USER_TYPE_SUCCESS';
export const USER_TYPE_FAILED = 'USER_TYPE_FAILED';

export const USER_TYPE_UPDATE_REQUEST = 'USER_TYPE_UPDATE_REQUEST';
export const USER_TYPE_UPDATE_SUCCESS = 'USER_TYPE_UPDATE_SUCCESS';
export const USER_TYPE_UPDATE_FAILED = 'USER_TYPE_UPDATE_FAILED';

export const AUTH_SUBSCRIPTION_REQUEST = 'AUTH_SUBSCRIPTION_REQUEST';
export const AUTH_SUBSCRIPTION_SUCCESS = 'AUTH_SUBSCRIPTION_SUCCESS';
export const AUTH_SUBSCRIPTION_FAILED = 'AUTH_SUBSCRIPTION_FAILED';

export const USER_BY_TYPE_REQUEST = 'USER_BY_TYPE_REQUEST';
export const USER_BY_TYPE_SUCCESS = 'USER_BY_TYPE_SUCCESS';
export const USER_BY_TYPE_FAILED = 'USER_BY_TYPE_FAILED';

export const STUDENT_GRADE_REQUEST = 'STUDENT_GRADE_REQUEST';
export const STUDENT_GRADE_SUCCESS = 'STUDENT_GRADE_SUCCESS';
export const STUDENT_GRADE_FAILED = 'STUDENT_GRADE_FAILED';

export const USER_LOGIN_FINALIZED = 'USER_LOGIN_FINALIZED';

export const STUDENT_WELCOME_VIDEO_REQUEST = 'STUDENT_WELCOME_VIDEO_REQUEST';
export const STUDENT_WELCOME_VIDEO_SUCCESS = 'STUDENT_WELCOME_VIDEO_SUCCESS';
export const STUDENT_WELCOME_VIDEO_FAILED = 'STUDENT_WELCOME_VIDEO_FAILED';

export const UPDATE_USER_INFORMATION_REQUEST =
  'UPDATE_USER_INFORMATION_REQUEST';
export const UPDATE_USER_INFORMATION_SUCCESS =
  'UPDATE_USER_INFORMATION_SUCCESS';
export const UPDATE_USER_INFORMATION_FAILED = 'UPDATE_USER_INFORMATION_FAILED';
