export const GET_STANDARD_REELS_REQUEST = 'GET_STANDARD_REELS_REQUEST';
export const GET_STANDARD_REELS_SUCCESS = 'GET_STANDARD_REELS_SUCCESS';
export const GET_STANDARD_REELS_FAILED = 'GET_STANDARD_REELS_FAILED';

export const GET_STANDARD_REEL_CONTENT_REQUEST =
  'GET_STANDARD_REEL_CONTENT_REQUEST';
export const GET_STANDARD_REEL_CONTENT_SUCCESS =
  'GET_STANDARD_REEL_CONTENT_SUCCESS';
export const GET_STANDARD_REEL_CONTENT_FAILED =
  'GET_STANDARD_REEL_CONTENT_FAILED';

export const GET_STANDARD_REEL_TUTOR_REQUEST =
  'GET_STANDARD_REEL_TUTOR_REQUEST';
export const GET_STANDARD_REEL_TUTOR_SUCCESS =
  'GET_STANDARD_REEL_TUTOR_SUCCESS';
export const GET_STANDARD_REEL_TUTOR_FAILED = 'GET_STANDARD_REEL_TUTOR_FAILED';

export const GET_FEATURED_REELS_REQUEST = 'GET_FEATURED_REELS_REQUEST';
export const GET_FEATURED_REELS_SUCCESS = 'GET_FEATURED_REELS_SUCCESS';
export const GET_FEATURED_REELS_FAILED = 'GET_FEATURED_REELS_FAILED';

export const GET_FEATURED_REELS_CONTENT_REQUEST =
  'GET_FEATURED_REELS_CONTENT_REQUEST';
export const GET_FEATURED_REELS_CONTENT_SUCCESS =
  'GET_FEATURED_REELS_CONTENT_SUCCESS';
export const GET_FEATURED_REELS_CONTENT_FAILED =
  'GET_FEATURED_REELS_CONTENT_FAILED';

export const RESET_REEL_REDUCER = 'RESET_REEL_REDUCER';
export const RESET_REEL_CONTENT_REDUCER = 'RESET_REEL_CONTENT_REDUCER';

export const WATCH_LATER_IDS_REQUEST = 'WATCH_LATER_IDS_REQUEST';
export const WATCH_LATER_IDS_SUCCESS = 'WATCH_LATER_IDS_SUCCESS';
export const WATCH_LATER_IDS_FAILED = 'WATCH_LATER_IDS_FAILED';

export const WATCH_LATER_VIDEO_CONTENT_REQUEST =
  'WATCH_LATER_VIDEO_CONTENT_REQUEST';
export const WATCH_LATER_VIDEO_CONTENT_SUCCESS =
  'WATCH_LATER_VIDEO_CONTENT_SUCCESS';
export const WATCH_LATER_VIDEO_CONTENT_FAILED =
  'WATCH_LATER_VIDEO_CONTENT_FAILED';

export const REMOVE_WATCH_LATER_VIDEO_REQUEST =
  'REMOVE_WATCH_LATER_VIDEO_REQUEST';
export const REMOVE_WATCH_LATER_VIDEO_SUCCESS =
  'REMOVE_WATCH_LATER_VIDEO_SUCCESS';
export const REMOVE_WATCH_LATER_VIDEO_FAILED =
  'REMOVE_WATCH_LATER_VIDEO_FAILED';

export const WATCH_LATER_VIDEO_CONTENT_LOAD_MORE =
  'WATCH_LATER_VIDEO_CONTENT_LOAD_MORE';

export const SUBMIT_REMAINDER_REQUEST = 'SUBMIT_REMAINDER_REQUEST';
export const SUBMIT_REMAINDER_SUCCESS = 'SUBMIT_REMAINDER_SUCCESS';
export const SUBMIT_REMAINDER_FAILED = 'SUBMIT_REMAINDER_FAILED';

export const SUBMIT_LIKE_REQUEST = 'SUBMIT_LIKE_REQUEST';
export const SUBMIT_LIKE_SUCCESS = 'SUBMIT_LIKE_SUCCESS';
export const SUBMIT_LIKE_FAIL = 'SUBMIT_LIKE_FAIL';

export const LIKED_VIDEO_CONTENT_SUCCESS = 'LIKED_VIDEO_CONTENT_SUCCESS';
export const LIKED_VIDEO_CONTENT_REQUEST = 'LIKED_VIDEO_CONTENT_REQUEST';
export const LIKED_VIDEO_CONTENT_FAIL = 'LIKED_VIDEO_CONTENT_FAIL';

export const SET_EMPTY_LIKE_CONTENT = 'SET_EMPTY_LIKE_CONTENT';

export const WATCH_LATER_IDS_LOAD_MORE = 'WATCH_LATER_IDS_LOAD_MORE';
