export const RESET_THEATER = 'RESET_THEATER';

export const GET_THEATER_CONTENT_FAILED = 'GET_THEATER_CONTENT_FAILED';
export const GET_THEATER_CONTENT_REQUEST = 'GET_THEATER_CONTENT_REQUEST';
export const GET_THEATER_CONTENT_SUCCESS = 'GET_THEATER_CONTENT_SUCCESS';

export const FETCH_TUTOR_INFO_REQUEST = 'FETCH_TUTOR_INFO_REQUEST';
export const FETCH_TUTOR_INFO_SUCCESS = 'FETCH_TUTOR_INFO_SUCCESS';
export const FETCH_TUTOR_INFO_FAILED = 'FETCH_TUTOR_INFO_FAILED';

export const THEATER_FULLSCREEN = 'THEATER_FULLSCREEN';

export const GET_THEATRE_WATCH_LATER_DATA_REQUEST =
  'GET_THEATRE_WATCH_LATER_DATA_REQUEST';
export const GET_THEATRE_WATCH_LATER_DATA_SUCCESS =
  'GET_THEATRE_WATCH_LATER_DATA_SUCCESS';
export const GET_THEATRE_WATCH_LATER_DATA_FAILED =
  'GET_THEATRE_WATCH_LATER_DATA_FAILED';

export const UPDATE_THEATRE_PLAYER_STATS = 'UPDATE_THEATRE_PLAYER_STATS';

export const GET_THEATRE_TUTOR_REEL_DATA_REQUEST =
  'GET_THEATRE_TUTOR_REEL_DATA_REQUEST';
export const GET_THEATRE_TUTOR_REEL_DATA_SUCCESS =
  'GET_THEATRE_TUTOR_REEL_DATA_SUCCESS';
export const GET_THEATRE_TUTOR_REEL_DATA_FAILED =
  'GET_THEATRE_TUTOR_REEL_DATA_FAILED';
export const GET_THEATRE_TUTOR_REEL_DATA_RESET =
  'GET_THEATRE_TUTOR_REEL_DATA_RESET';

export const GET_MID_VIDEO_ASSESSMENT_CONTENT_SUCCESS =
  'GET_MID_VIDEO_ASSESSMENT_CONTENT_SUCCESS';
export const GET_MID_VIDEO_ASSESSMENT_CONTENT_REQUEST =
  'GET_MID_VIDEO_ASSESSMENT_CONTENT_REQUEST';
export const GET_MID_VIDEO_ASSESSMENT_CONTENT_FAIL =
  'GET_MID_VIDEO_ASSESSMENT_CONTENT_FAIL';

export const UPDATE_PLAYER_LAST_WATCHED_REQUEST =
  'UPDATE_PLAYER_LAST_WATCHED_REQUEST';
export const UPDATE_PLAYER_LAST_WATCHED_SUCCESS =
  'UPDATE_PLAYER_LAST_WATCHED_SUCCESS';
export const UPDATE_PLAYER_LAST_WATCHED_FAILED =
  'UPDATE_PLAYER_LAST_WATCHED_FAILED';

export const GET_MID_AND_END_DETAILS_SUCCESS =
  'GET_MID_AND_END_DETAILS_SUCCESS';
export const GET_MID_AND_END_DETAILS_REQUEST =
  'GET_MID_AND_END_DETAILS_REQUEST';
export const GET_MID_AND_END_DETAILS_FAIL = 'GET_MID_AND_END_DETAILS_FAIL';

export const SET_THEATRE_SELECTED_CONTENT = 'SET_THEATRE_SELECTED_CONTENT';

export const THEATER_SUMMARY_REQUEST = 'THEATER_SUMMARY_REQUEST';
export const UPDATE_SUMMARY_TEXT_SUCCESS = 'UPDATE_SUMMARY_TEXT_SUCCESS';
export const THEATER_SUMMARY_FAILED = 'THEATER_SUMMARY_FAILED';
export const GET_THEATER_SUMMARY_SUCCESS = 'GET_THEATER_SUMMARY_SUCCESS';

export const RESET_SUMMARY_REQUEST = 'RESET_SUMMARY_REQUEST';
export const RESET_SUMMARY_SUCCESS = 'RESET_SUMMARY_SUCCESS';
export const RESET_SUMMARY_FAILED = 'RESET_SUMMARY_FAILED';

export const DOWNLOAD_SUMMARY_REQUEST = 'DOWNLOAD_SUMMARY_REQUEST';
export const DOWNLOAD_SUMMARY_SUCCESS = 'DOWNLOAD_SUMMARY_SUCCESS';
export const DOWNLOAD_SUMMARY_FAILED = 'DOWNLOAD_SUMMARY_FAILED';
export const GET_DOCUMENTS_REQUEST = 'GET_DOCUMENTS_REQUEST';
export const GET_DOCUMENTS_SUCCESS = 'GET_DOCUMENTS_SUCCESS';
export const GET_DOCUMENTS_FAILED = 'GET_DOCUMENTS_FAILED';
export const GET_LINKED_DOCUMENTS_SUCCESS = 'GET_LINKED_DOCUMENTS_SUCCESS';
export const GET_END_VIDEO_ASSESSMENT_REQUEST =
  'GET_END_VIDEO_ASSESSMENT_REQUEST';
export const GET_END_VIDEO_ASSESSMENT_SUCCESS =
  'GET_END_VIDEO_ASSESSMENT_SUCCESS';
export const GET_END_VIDEO_ASSESSMENT_FAILED =
  'GET_END_VIDEO_ASSESSMENT_FAILED';

export const GET_END_VIDEO_ASSESSMENT_ATTEMPTS_REQUEST =
  'GET_END_VIDEO_ASSESSMENT_ATTEMPTS_REQUEST';
export const GET_END_VIDEO_ASSESSMENT_ATTEMPTS_SUCCESS =
  'GET_END_VIDEO_ASSESSMENT_ATTEMPTS_SUCCESS';
export const GET_END_VIDEO_ASSESSMENT_ATTEMPTS_FAILED =
  'GET_END_VIDEO_ASSESSMENT_ATTEMPTS_FAILED';

export const CREATE_END_VIDEO_ASSESSMENT_ATTEMPT_REQUEST =
  'CREATE_END_VIDEO_ASSESSMENT_ATTEMPT_REQUEST';
export const CREATE_END_VIDEO_ASSESSMENT_ATTEMPT_SUCCESS =
  'CREATE_END_VIDEO_ASSESSMENT_ATTEMPT_SUCCESS';
export const CREATE_END_VIDEO_ASSESSMENT_ATTEMPT_FAILED =
  'CREATE_END_VIDEO_ASSESSMENT_ATTEMPT_FAILED';

export const UPDATE_END_VIDEO_ASSESSMENT_ATTEMPT_REQUEST =
  'UPDATE_END_VIDEO_ASSESSMENT_ATTEMPT_REQUEST';
export const UPDATE_END_VIDEO_ASSESSMENT_ATTEMPT_SUCCESS =
  'UPDATE_END_VIDEO_ASSESSMENT_ATTEMPT_SUCCESS';
export const UPDATE_END_VIDEO_ASSESSMENT_ATTEMPT_FAILED =
  'UPDATE_END_VIDEO_ASSESSMENT_ATTEMPT_FAILED';

export const SUBMIT_END_VIDEO_ASSESSMENT_ATTEMPT_REQUEST =
  'SUBMIT_END_VIDEO_ASSESSMENT_ATTEMPT_REQUEST';
export const SUBMIT_END_VIDEO_ASSESSMENT_ATTEMPT_SUCCESS =
  'SUBMIT_END_VIDEO_ASSESSMENT_ATTEMPT_SUCCESS';
export const SUBMIT_END_VIDEO_ASSESSMENT_ATTEMPT_FAILED =
  'SUBMIT_END_VIDEO_ASSESSMENT_ATTEMPT_FAILED';
export const GET_ASSESSMENT_ATTEMPTS_REQUEST =
  'GET_ASSESSMENT_ATTEMPTS_REQUEST';
export const GET_ASSESSMENT_ATTEMPTS_SUCCESS =
  'GET_ASSESSMENT_ATTEMPTS_SUCCESS';
export const GET_ASSESSMENT_ATTEMPTS_FAILED = 'GET_ASSESSMENT_ATTEMPTS_FAILED';

export const POST_ASSESSMENT_ATTEMPTS_REQUEST =
  'POST_ASSESSMENT_ATTEMPTS_REQUEST';
export const POST_ASSESSMENT_ATTEMPTS_SUCCESS =
  'POST_ASSESSMENT_ATTEMPTS_SUCCESS';
export const POST_ASSESSMENT_ATTEMPTS_FAILED =
  'POST_ASSESSMENT_ATTEMPTS_FAILED';

export const SINGLE_QUESTION_UPDATE_SUCCESS = 'SINGLE_QUESTION_UPDATE_SUCCESS';
export const SINGLE_QUESTION_UPDATE_REQUEST = 'SINGLE_QUESTION_UPDATE_REQUEST';
export const SINGLE_QUESTION_UPDATE_FAIL = 'SINGLE_QUESTION_UPDATE_FAIL';

export const SUBMIT_QUESTION_SUCCESS = 'SUBMIT_QUESTION_SUCCESS';
export const SUBMIT_QUESTION_FAIL = 'SUBMIT_QUESTION_FAIL';
export const SUBMIT_QUESTION_REQUEST = 'SUBMIT_QUESTION_REQUEST';

export const GET_QUESTION_RESULTS_SUCCESS = 'GET_QUESTION_RESULTS_SUCCESS';
export const GET_QUESTION_RESULTS_REQUEST = 'GET_QUESTION_RESULTS_REQUEST';
export const GET_QUESTION_RESULTS_FAIL = 'GET_QUESTION_RESULTS_FAIL';

export const ATTEMPT_CREATION_LOADING_SUCCESS =
  'ATTEMPT_CREATION_LOADING_SUCCESS';

export const RESET_ASSESSMENT_ATTEMPT = 'RESET_ASSESSMENT_ATTEMPT';

export const RESET_END_VIDEO_ASSESSMENT_ATTEMPT_DATA =
  'RESET_END_VIDEO_ASSESSMENT_ATTEMPT_DATA';
