export const HOVER_ON_SUBJECT_REEL_CONTENT = 'HOVER_ON_SUBJECT_REEL_CONTENT';

export const INITIALIZE_SUBJECTS_DATA_FAIL = 'INITIALIZE_SUBJECTS_DATA_FAIL';
export const INITIALIZE_SUBJECTS_DATA_REQUEST =
  'INITIALIZE_SUBJECTS_DATA_REQUEST';
export const INITIALIZE_SUBJECTS_DATA_SUCCESS =
  'INITIALIZE_SUBJECTS_DATA_SUCCESS';
export const INITIALIZE_SUBJECT_TUTORS_FAIL = 'INITIALIZE_SUBJECT_TUTORS_FAIL';
export const INITIALIZE_SUBJECT_TUTORS_REQUEST =
  'INITIALIZE_SUBJECT_TUTORS_REQUEST';
export const INITIALIZE_SUBJECT_TUTORS_SUCCESS =
  'INITIALIZE_SUBJECT_TUTORS_SUCCESS';
export const INITIALIZE_SUBJECT_TUTOR_CONTENTS_FAIL =
  'INITIALIZE_SUBJECT_TUTOR_CONTENTS_FAIL';
export const INITIALIZE_SUBJECT_TUTOR_CONTENTS_REQUEST =
  'INITIALIZE_SUBJECT_TUTOR_CONTENTS_REQUEST';
export const INITIALIZE_SUBJECT_TUTOR_CONTENTS_SUCCESS =
  'INITIALIZE_SUBJECT_TUTOR_CONTENTS_SUCCESS';
export const INITIALIZE_SUBJECT_CONTENTS_FAIL =
  'INITIALIZE_SUBJECT_CONTENTS_FAIL';
export const INITIALIZE_SUBJECT_CONTENTS_REQUEST =
  'INITIALIZE_SUBJECT_CONTENTS_REQUEST';
export const INITIALIZE_SUBJECT_CONTENTS_SUCCESS =
  'INITIALIZE_SUBJECT_CONTENTS_SUCCESS';

export const UPDATE_SUBJECTS_REEL_FAIL = 'UPDATE_SUBJECT_REEL_FAIL';
export const UPDATE_SUBJECTS_REEL_REQUEST = 'UPDATE_SUBJECT_REEL_REQUEST';
export const UPDATE_SUBJECTS_REEL_SUCCESS = 'UPDATE_SUBJECT_REEL_SUCCESS';

export const UPDATE_SUBJECT_CONTENTS_FAIL = 'UPDATE_SUBJECT_CONTENTS_FAIL';
export const UPDATE_SUBJECT_CONTENTS_REQUEST =
  'UPDATE_SUBJECT_CONTENTS_REQUEST';
export const UPDATE_SUBJECT_CONTENTS_SUCCESS =
  'UPDATE_SUBJECT_CONTENTS_SUCCESS';
export const UPDATE_TUTORS_SUCCESS = 'UPDATE_TUTORS_SUCCESS';

export const UPDATE_TUTOR_ON_CLICK_TOGGLE = 'UPDATE_TUTOR_ON_CLICK_TOGGLE';
export const UPDATE_TUTOR_CONTENTS_FAIL = 'UPDATE_TUTOR_CONTENTS_FAIL';
export const UPDATE_TUTOR_CONTENTS_REQUEST = 'UPDATE_TUTOR_CONTENTS_REQUEST';
export const UPDATE_TUTOR_CONTENTS_SUCCESS = 'UPDATE_TUTOR_CONTENTS_SUCCESS';

export const RESET_SUBJECTS_REDUCER_DATA = 'RESET_SUBJECTS_REDUCER_DATA';
