export const CREATE_ASSESSMENT_FAILED = 'CREATE_ASSESSMENT_FAILED';
export const CREATE_ASSESSMENT_REQUEST = 'CREATE_ASSESSMENT_REQUEST';
export const CREATE_ASSESSMENT_SUCCESS = 'CREATE_ASSESSMENT_SUCCESS';

export const CREATE_VIDEO_FAILED = 'CREATE_VIDEO_FAILED';
export const CREATE_VIDEO_REQUEST = 'CREATE_VIDEO_REQUEST';
export const CREATE_VIDEO_SUCCESS = 'CREATE_VIDEO_SUCCESS';

export const CREATE_LINKED_DOCUMENT_FAILED = 'CREATE_LINKED_DOCUMENT_FAILED';
export const CREATE_LINKED_DOCUMENT_REQUEST = 'CREATE_LINKED_DOCUMENT_REQUEST';
export const CREATE_LINKED_DOCUMENT_SUCCESS = 'CREATE_LINKED_DOCUMENT_SUCCESS';

export const DOCUMENT_UPLOAD_FAILED = 'DOCUMENT_UPLOAD_FAILED';
export const DOCUMENT_UPLOAD_REQUEST = 'DOCUMENT_UPLOAD_REQUEST';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';

export const CREATE_CONTENT_RESET = 'CREATE_CONTENT_RESET';
