export const GET_COUNTRIES_DATA_FAILED = 'GET_COUNTRIES_DATA_FAILED';
export const GET_COUNTRIES_DATA_REQUEST = 'GET_COUNTRIES_DATA_REQUEST';
export const GET_COUNTRIES_DATA_SUCCESS = 'GET_COUNTRIES_DATA_SUCCESS';
export const RESET_COUNTRIES_DATA = 'RESET_COUNTRIES_DATA';

export const GET_GRADES_DATA_FAILED = 'GET_GRADES_DATA_FAILED';
export const GET_GRADES_DATA_REQUEST = 'GET_GRADES_DATA_REQUEST';
export const GET_GRADES_DATA_SUCCESS = 'GET_GRADES_DATA_SUCCESS';
export const RESET_GRADES_DATA = 'RESET_GRADES_DATA';

export const GET_SCHOOLS_DATA_FAILED = 'GET_SCHOOLS_DATA_FAILED';
export const GET_SCHOOLS_DATA_REQUEST = 'GET_SCHOOLS_DATA_REQUEST';
export const GET_SCHOOLS_DATA_SUCCESS = 'GET_SCHOOLS_DATA_SUCCESS';
export const RESET_SCHOOLS_DATA = 'RESET_SCHOOLS_DATA';

export const GET_SUBJECTS_DATA_FAILED = 'GET_SUBJECTS_DATA_FAILED';
export const GET_SUBJECTS_DATA_REQUEST = 'GET_SUBJECTS_DATA_REQUEST';
export const GET_SUBJECTS_DATA_SUCCESS = 'GET_SUBJECTS_DATA_SUCCESS';
export const RESET_SUBJECTS_DATA = 'RESET_SUBJECTS_DATA';

export const GET_SYLLABUSES_DATA_FAILED = 'GET_SYLLABUSES_DATA_FAILED';
export const GET_SYLLABUSES_DATA_REQUEST = 'GET_SYLLABUSES_DATA_REQUEST';
export const GET_SYLLABUSES_DATA_SUCCESS = 'GET_SYLLABUSES_DATA_SUCCESS';
export const RESET_SYLLABUSES_DATA = 'RESET_SYLLABUSES_DATA';

export const SET_SELECTED_COUNTRY_LIST = 'SET_SELECTED_COUNTRY_LIST';
export const SET_SELECTED_GRADE_LIST = 'SET_SELECTED_GRADE_LIST';
export const SET_SELECTED_SCHOOL_LIST = 'SET_SELECTED_SCHOOL_LIST';
export const SET_SELECTED_SYLLABUS_LIST = 'SET_SELECTED_SYLLABUS_LIST';
export const SET_SELECTED_SUBJECT_LIST = 'SET_SELECTED_SUBJECT_LIST';

export const REMOVE_UNSELECTED_GRADES = 'REMOVE_UNSELECTED_GRADES';
export const REMOVE_UNSELECTED_SCHOOLS = 'REMOVE_UNSELECTED_SCHOOLS';
export const REMOVE_UNSELECTED_SUBJECTS = 'REMOVE_UNSELECTED_SUBJECTS';
export const REMOVE_UNSELECTED_SYLLABUSES = 'REMOVE_UNSELECTED_SYLLABUSES';
