export const GET_DIVISION_HIERARCHY_FAILED = 'GET_DIVISION_HIERARCHY_FAILED';
export const GET_DIVISION_HIERARCHY_REQUEST = 'GET_DIVISION_HIERARCHY_REQUEST';
export const GET_DIVISION_HIERARCHY_SUCCESS = 'GET_DIVISION_HIERARCHY_SUCCESS';
