export const GET_NOTIFICATION_REQUEST = 'GET_NOTIFICATION_REQUEST';
export const GET_NOTIFICATION_SUCCESS = 'GET_NOTIFICATION_SUCCESS';
export const GET_NOTIFICATION_FAILED = 'GET_NOTIFICATION_FAILED';

export const HEADER_NOTIFICATION_REQUEST = 'HEADER_NOTIFICATION_REQUEST';
export const HEADER_NOTIFICATION_SUCCESS = 'HEADER_NOTIFICATION_SUCCESS';
export const HEADER_NOTIFICATION_FAILED = 'HEADER_NOTIFICATION_FAILED';

export const READ_NOTIFICATION_REQUEST = 'READ_NOTIFICATION_REQUEST';
export const READ_NOTIFICATION_SUCCESS = 'READ_NOTIFICATION_SUCCESS';
export const READ_NOTIFICATION_FAILED = 'READ_NOTIFICATION_FAILED';
export const HEADER_NOTIFICATION_RESET = 'HEADER_NOTIFICATION_RESET';
