export const TRIAL_SUBJECT_FAILED = 'TRIAL_SUBJECT_FAILED';
export const TRIAL_SUBJECT_REQUEST = 'TRIAL_SUBJECT_REQUEST';
export const TRIAL_SUBJECT_RESET = 'TRIAL_SUBJECT_RESET';
export const TRIAL_SUBJECT_SUCCESS = 'TRIAL_SUBJECT_SUCCESS';

export const SELECT_TOGGLE_SUBJECT = 'SELECT_TOGGLE_SUBJECT';
export const SELECT_TOGGLE_SUBJECT_FILTER = 'SELECT_TOGGLE_SUBJECT_FILTER';

export const TRIAL_GRADE_REQUEST = 'TRIAL_GRADE_REQUEST';
export const TRIAL_GRADE_SUCCESS = 'TRIAL_GRADE_SUCCESS';
export const TRIAL_GRADE_FAILED = 'TRIAL_GRADE_FAILED';

export const TRIAL_USER_REQUEST = 'TRIAL_USER_REQUEST';
export const TRIAL_USER_SUCCESS = 'TRIAL_USER_SUCCESS';
export const TRIAL_USER_FAILED = 'TRIAL_USER_FAILED';

export const SUBSCRIPTION_REQUEST = 'SUBSCRIPTION_REQUEST';
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS';
export const SUBSCRIPTION_FAILED = 'SUBSCRIPTION_FAILED';

export const TRIAL_SELECT_SUBSCRIPTION = 'TRIAL_SELECT_SUBSCRIPTION';

export const GET_ALL_SYLLABUSES_REQUEST = 'GET_ALL_SYLLABUSES_REQUEST';
export const TRIAL_SYLLABUSES_SUCCESS = 'TRIAL_SYLLABUSES_SUCCESS';
export const TRIAL_SYLLABUSES_FAILED = 'TRIAL_SYLLABUSES_FAILED';

export const TRIAL_GRADES_FAILED = 'TRIAL_GRADES_FAILED';
export const TRIAL_GRADES_REQUEST = 'TRIAL_GRADES_REQUEST';
export const TRIAL_GRADES_RESET = 'TRIAL_GRADES_RESET';
export const TRIAL_GRADES_SUCCESS = 'TRIAL_GRADES_SUCCESS';

export const TRIAL_PRODUCTS_REQUEST = 'TRIAL_PRODUCTS_REQUEST';
export const TRIAL_PRODUCTS_SUCCESS = 'TRIAL_PRODUCTS_SUCCESS';
export const TRIAL_PRODUCTS_FAILED = 'TRIAL_PRODUCTS_FAILED';

export const TRIAL_SELECT_PRODUCT = 'TRIAL_SELECT_PRODUCT';

export const TRIAL_PRODUCT_IDS_REQUEST = 'TRIAL_PRODUCT_IDS_REQUEST';
export const TRIAL_PRODUCT_IDS_SUCCESS = 'TRIAL_PRODUCT_IDS_SUCCESS';
export const TRIAL_PRODUCT_IDS_FAILED = 'TRIAL_PRODUCT_IDS_FAILED';

export const TRIAL_PRODUCT_CONTENT_REQUEST = 'TRIAL_PRODUCT_CONTENT_REQUEST';
export const TRIAL_PRODUCT_CONTENT_SUCCESS = 'TRIAL_PRODUCT_CONTENT_SUCCESS';
export const TRIAL_PRODUCT_CONTENT_FAILED = 'TRIAL_PRODUCT_CONTENT_FAILED';

export const TRIAL_SYLLABUS_REQUEST = 'TRIAL_SYLLABUS_REQUEST';
export const TRIAL_SYLLABUS_SUCCESS = 'TRIAL_SYLLABUS_SUCCESS';
export const TRIAL_SYLLABUS_FAILED = 'TRIAL_SYLLABUS_FAILED';

export const TRIAL_GRADE_BY_ID_REQUEST = 'TRIAL_GRADE_BY_ID_REQUEST';
export const TRIAL_GRADE_BY_ID_SUCCESS = 'TRIAL_GRADE_BY_ID_SUCCESS';
export const TRIAL_GRADE_BY_ID_FAILED = 'TRIAL_GRADE_BY_ID_FAILED';

export const TRIAL_CURRENCY_REQUEST = 'TRIAL_CURRENCY_REQUEST';
export const TRIAL_CURRENCY_SUCCESS = 'TRIAL_CURRENCY_SUCCESS';
export const TRIAL_CURRENCY_FAILED = 'TRIAL_CURRENCY_FAILED';

export const TRIAL_SUBMIT_REQUEST = 'TRIAL_SUBMIT_REQUEST';
export const TRIAL_SUBMIT_SUCCESS = 'TRIAL_SUBMIT_SUCCESS';
export const TRIAL_SUBMIT_FAILED = 'TRIAL_SUBMIT_FAILED';

export const RESET_PRODUCTS = 'RESET_PRODUCTS';

export const RESET_TRIAL = 'RESET_TRIAL';
