export const GET_ALL_ADMINS_FAILED = 'GET_ALL_ADMINS_FAILED';
export const GET_ALL_ADMINS_REQUEST = 'GET_ALL_ADMINS_REQUEST';
export const GET_ALL_ADMINS_SUCCESS = 'GET_ALL_ADMINS_SUCCESS';

export const GET_ALL_PARENTS_FAILED = 'GET_ALL_PARENTS_FAILED';
export const GET_ALL_PARENTS_REQUEST = 'GET_ALL_PARENTS_REQUEST';
export const GET_ALL_PARENTS_SUCCESS = 'GET_ALL_PARENTS_SUCCESS';

export const GET_ALL_STUDENTS_FAILED = 'GET_ALL_STUDENTS_FAILED';
export const GET_ALL_STUDENTS_REQUEST = 'GET_ALL_STUDENTS_REQUEST';
export const GET_ALL_STUDENTS_SUCCESS = 'GET_ALL_STUDENTS_SUCCESS';

export const GET_ALL_TUTORS_FAILED = 'GET_ALL_TUTORS_FAILED';
export const GET_ALL_TUTORS_REQUEST = 'GET_ALL_TUTORS_REQUEST';
export const GET_ALL_TUTORS_SUCCESS = 'GET_ALL_TUTORS_SUCCESS';

export const GET_ALL_USERS_FAILED = 'GET_ALL_USERS_FAILED';
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';

//individual user detail types
export const GET_USER_DETAILS_FAILED = 'GET_USER_DETAILS_FAILED';
export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS__SUCCESS = 'GET_USER_DETAILS__SUCCESS';

//country code & retrive country details
export const GET_COUNTRY_DETAILS_FAILED = 'GET_COUNTRY_DETAILS_FAILED';
export const GET_COUNTRY_DETAILS_REQUEST = 'GET_COUNTRY_DETAILS_REQUEST';
export const GET_COUNTRY_DETAILS__SUCCESS = 'GET_COUNTRY_DETAILS__SUCCESS';

//user grade retrive
export const GET_GRADE_DETAILS_FAILED = 'GET_GRADE_DETAILS_FAILED';
export const GET_GRADE_DETAILS_REQUEST = 'GET_GRADE_DETAILS_REQUEST';
export const GET_GRADE_DETAILS__SUCCESS = 'GET_GRADE_DETAILS__SUCCESS';

//user Syllabuses  retrive
export const GET_SYLLABUS_DETAILS_FAILED = 'GET_SYLLABUS_DETAILS_FAILED';
export const GET_SYLLABUS_DETAILS_REQUEST = 'GET_SYLLABUS_DETAILS_REQUEST';
export const GET_SYLLABUS_DETAILS__SUCCESS = 'GET_SYLLABUS_DETAILS__SUCCESS';

//user SchoolData retrive
export const GET_SCHOOL_DETAILS_FAILED = 'GET_SCHOOL_DETAILS_FAILED';
export const GET_SCHOOL_DETAILS_REQUEST = 'GET_SCHOOL_DETAILS_REQUEST';
export const GET_SCHOOL_DETAILS__SUCCESS = 'GET_SCHOOL_DETAILS__SUCCESS';

//user Subject Data retrive
export const GET_SUBJECTS_DETAILS_FAILED = 'GET_SUBJECTS_DETAILS_FAILED';
export const GET_SUBJECTS_DETAILS_REQUEST = 'GET_SUBJECTS_DETAILS_REQUEST';
export const GET_SUBJECTS_DETAILS_SUCCESS = 'GET_SUBJECTS_DETAILS_SUCCESS';

//user tutor Grade Data retrive
export const GET_TUTOR_GRADES_FAILED = 'GET_TUTOR_GRADES_FAILED';
export const GET_TUTOR_GRADES_REQUEST = 'GET_TUTOR_GRADES_REQUEST';
export const GET_TUTOR_GRADES_SUCCESS = 'GET_TUTOR_GRADES_SUCCESS';

//user tutor syllabus data retrive
export const GET_TUTOR_SYLLABUS_FAILED = 'GET_TUTOR_SYLLABUS_FAILED';
export const GET_TUTOR_SYLLABUS_REQUEST = 'GET_TUTOR_SYLLABUS_REQUEST';
export const GET_TUTOR_SYLLABUS_SUCCESS = 'GET_TUTOR_SYLLABUS_SUCCESS';

//user tutor countrys
export const GET_TUTOR_COUNTRY_FAILED = 'GET_TUTOR_COUNTRY_FAILED';
export const GET_TUTOR_COUNTRY_REQUEST = 'GET_TUTOR_COUNTRY_REQUEST';
export const GET_TUTOR_COUNTRY_SUCCESS = 'GET_TUTOR_COUNTRY_SUCCESS';

//clear all states
export const RESET_INDIVIDUAL_USER_MANAGEMENT =
  'RESET_INDIVIDUAL_USER_MANAGEMENT';

export const GET_USER_GRADES_REQUEST = 'GET_USER_GRADES_REQUEST';
export const GET_USER_GRADES_SUCCESS = 'GET_USER_GRADES_SUCCESS';
export const GET_USER_GRADES_FAILED = 'GET_USER_GRADES_FAILED';

export const GET_USER_COUNTRIES_REQUEST = 'GET_USER_COUNTRIES_REQUEST';
export const GET_USER_COUNTRIES_SUCCESS = 'GET_USER_COUNTRIES_SUCCESS';
export const GET_USER_COUNTRIES_FAILED = 'GET_USER_COUNTRIES_FAILED';

export const GET_USER_SYLLABUSES_REQUEST = 'GET_USER_SYLLABUSES_REQUEST';
export const GET_USER_SYLLABUSES_SUCCESS = 'GET_USER_SYLLABUSES_SUCCESS';
export const GET_USER_SYLLABUSES_FAILED = 'GET_USER_SYLLABUSES_FAILED';


// tutor fetch all subjects by subject ids
export const GET_TUTOR_SUBJECTS_REQUEST = 'GET_TUTOR_SUBJECTS_REQUEST';
export const GET_TUTOR_SUBJECTS_SUCCESS = 'GET_TUTOR_SUBJECTS_SUCCESS';
export const GET_TUTOR_SUBJECTS_FAIL = 'GET_TUTOR_SUBJECTS_FAIL';
