export const RESET_DOCUMENT_VIEW = 'RESET_DOCUMENT_VIEW';

export const GET_DOC_RELATED_VIDEOS_REQUEST = 'GET_DOC_RELATED_VIDEOS_REQUEST';
export const GET_DOC_RELATED_VIDEOS_SUCCESS = 'GET_DOC_RELATED_VIDEOS_SUCCESS';
export const GET_DOC_RELATED_VIDEOS_FAILED = 'GET_DOC_RELATED_VIDEOS_FAILED';

export const GET_DOC_RELATED_ASSESSMENTS_REQUEST =
  'GET_DOC_RELATED_ASSESSMENTS_REQUEST';
export const GET_DOC_RELATED_ASSESSMENTS_SUCCESS =
  'GET_DOC_RELATED_ASSESSMENTS_SUCCESS';
export const GET_DOC_RELATED_ASSESSMENTS_FAILED =
  'GET_DOC_RELATED_ASSESSMENTS_FAILED';

export const GET_DOC_RELATED_DOCUMENTS_REQUEST =
  'GET_DOC_RELATED_DOCUMENTS_REQUEST';
export const GET_DOC_RELATED_DOCUMENTS_SUCCESS =
  'GET_DOC_RELATED_DOCUMENTS_SUCCESS';
export const GET_DOC_RELATED_DOCUMENTS_FAILED =
  'GET_DOC_RELATED_DOCUMENTS_FAILED';

export const GET_DOC_RELATED_NOTES_REQUEST = 'GET_DOC_RELATED_NOTES_REQUEST';
export const GET_DOC_RELATED_NOTES_SUCCESS = 'GET_DOC_RELATED_NOTES_SUCCESS';
export const GET_DOC_RELATED_NOTES_FAILED = 'GET_DOC_RELATED_NOTES_FAILED';

export const SAVE_DOC_RELATED_NOTES_REQUEST = 'SAVE_DOC_RELATED_NOTES_REQUEST';
export const SAVE_DOC_RELATED_NOTES_SUCCESS = 'SAVE_DOC_RELATED_NOTES_SUCCESS';
export const SAVE_DOC_RELATED_NOTES_FAILED = 'SAVE_DOC_RELATED_NOTES_FAILED';

export const GET_DOCUMENT_DATA_REQUEST = 'GET_DOCUMENT_DATA_REQUEST';
export const GET_DOCUMENT_DATA_SUCCESS = 'GET_DOCUMENT_DATA_SUCCESS';
export const GET_DOCUMENT_DATA_FAILED = 'GET_DOCUMENT_DATA_FAILED';
