export const USER_SELECTED_SUBSCRIPTION_REQUEST =
  'USER_SELECTED_SUBSCRIPTION_REQUEST';
export const USER_SELECTED_SUBSCRIPTION_SUCCESS =
  'USER_SELECTED_SUBSCRIPTION_SUCCESS';
export const USER_SELECTED_SUBSCRIPTION_FAILED =
  'USER_SELECTED_SUBSCRIPTION_FAILED';
export const RESET_PRODUCT_SUBSCRIPTION = 'RESET_PRODUCT_SUBSCRIPTION';

export const GET_SUBSCRIBED_PLAN_PRODUCTS_REQUEST =
  'GET_SUBSCRIBED_PLAN_PRODUCTS_REQUEST';
export const GET_SUBSCRIBED_PLAN_PRODUCTS_SUCCESS =
  'GET_SUBSCRIBED_PLAN_PRODUCTS_SUCCESS';
export const GET_SUBSCRIBED_PLAN_PRODUCTS_FAILED =
  'GET_SUBSCRIBED_PLAN_PRODUCTS_FAILED';
export const SET_SELECTED_SUBSCRIPTION = 'SET_SELECTED_SUBSCRIPTION';

export const SUBSCRIPTION_PRODUCT_FAILED = 'SUBSCRIPTION_PRODUCT_FAILED';
export const SUBSCRIPTION_PRODUCT_SUCCESS = 'SUBSCRIPTION_PRODUCT_SUCCESS';
export const SUBSCRIPTION_PRODUCT_REQUEST = 'SUBSCRIPTION_PRODUCT_REQUEST';

export const PRODUCT_CONTENT_VIDEO_REQUEST = 'PRODUCT_CONTENT_VIDEO_REQUEST';
export const PRODUCT_CONTENT_VIDEO_SUCCESS = 'PRODUCT_CONTENT_VIDEO_SUCCESS';
export const PRODUCT_CONTENT_VIDEO_FAILED = 'PRODUCT_CONTENT_VIDEO_FAILED';

export const PRODUCT_CONTENT_DOCUMENTS_REQUEST =
  'PRODUCT_CONTENT_DOCUMENTS_REQUEST';
export const PRODUCT_CONTENT_DOCUMENTS_SUCCESS =
  'PRODUCT_CONTENT_DOCUMENTS_SUCCESS';
export const PRODUCT_CONTENT_DOCUMENTS_FAILED =
  'PRODUCT_CONTENT_DOCUMENTS_FAILED';

export const PRODUCT_CONTENT_ASSESMENTS_REQUEST =
  'PRODUCT_CONTENT_ASSESMENTS_REQUEST';
export const PRODUCT_CONTENT_ASSESMENTS_SUCCESS =
  'PRODUCT_CONTENT_ASSESMENTS_SUCCESS';
export const PRODUCT_CONTENT_ASSESMENTS_FAILED =
  'PRODUCT_CONTENT_ASSESMENTS_FAILED';

export const GET_ALLOWED_PRODUCTS_SUCCESS = 'GET_ALLOWED_PRODUCTS_SUCCESS';
export const GET_ALLOWED_PRODUCTS_REQUEST = 'GET_ALLOWED_PRODUCTS_REQUEST';
export const GET_ALLOWED_PRODUCTS_FAIL = 'GET_ALLOWED_PRODUCTS_FAIL';

export const SET_IN_CART_PRODUCTS = 'SET_IN_CART_PRODUCTS';
export const SET_TOGGLE_INCART_PRODUCT = 'SET_TOGGLE_INCART_PRODUCT';
