export const SummaryData = {
  Maths: {
    1: [
      {
        index: 1,
        text: '10 Hundreds make 1000',
        timeStart: '00:00',
        timeEnd: '00:45',
        currentTime: 0,
      },
      {
        index: 2,
        text: 'Reading and Writing Numbers up to 10 000',
        timeStart: '00:45',
        timeEnd: '01:45',
        currentTime: 45,
      },
      {
        index: 3,
        text: 'Recap',
        timeStart: '01:45',
        timeEnd: '02:00',
        currentTime: 105,
      },
    ],
    2: [
      {
        index: 1,
        text: 'Lesson objectives',
        timeStart: '00:00',
        timeEnd: '00:15',
        currentTime: 0,
      },
      {
        index: 2,
        text: 'Count, read and write numbers to 10 000',
        timeStart: '00:15',
        timeEnd: '01:00',
        currentTime: 15,
      },
      {
        index: 3,
        text: 'Counting in thousands up to 10 000',
        timeStart: '01:00',
        timeEnd: '01:30',
        currentTime: 60,
      },
      {
        index: 4,
        text: 'Writing numbers in numerals and words',
        timeStart: '01:30',
        timeEnd: '02:00',
        currentTime: 90,
      },
      {
        index: 5,
        text: 'Understanding place values',
        timeStart: '02:00',
        timeEnd: '03:20',
        currentTime: 120,
      },
      {
        index: 6,
        text: 'Find the missing numbers',
        timeStart: '03:20',
        timeEnd: '04:30',
        currentTime: 200,
      },
      {
        index: 7,
        text: 'Comparing Numbers',
        timeStart: '04:30',
        timeEnd: '05:37',
        currentTime: 270,
      },
    ],
    3: [],
    4: [
      {
        index: 1,
        text: 'Reading Numbers to 10000',
        timeStart: '00:00',
        timeEnd: '01:00',
        currentTime: 0,
      },
      {
        index: 2,
        text: 'Number sequencing',
        timeStart: '01:00',
        timeEnd: '01:40',
        currentTime: 60,
      },
      {
        index: 3,
        text: 'Writing numbers in words',
        timeStart: '01:40',
        timeEnd: '02:00',
        currentTime: 100,
      },
      {
        index: 4,
        text: 'Writing numbers in numerals',
        timeStart: '02:00',
        timeEnd: '02:40',
        currentTime: 120,
      },
      {
        index: 5,
        text: 'Writing numbers in numerals and words',
        timeStart: '02:40',
        timeEnd: '04:10',
        currentTime: 160,
      },
      {
        index: 6,
        text: 'Assignment',
        timeStart: '04:10',
        timeEnd: '04:47',
        currentTime: 250,
      },
    ],
    5: [
      {
        index: 1,
        text: 'Arrange the numbers in thousands, hundreds, tens and ones',
        timeStart: '00:00',
        timeEnd: '00:00',
        currentTime: 0,
      },
      {
        index: 2,
        text: 'Compare the thousands',
        timeStart: '01:30',
        timeEnd: '01:30',
        currentTime: 90,
      },
      {
        index: 3,
        text: 'Compare the hundreds',
        timeStart: '02:10',
        timeEnd: '02:10',
        currentTime: 130,
      },
      {
        index: 4,
        text: 'Arranging the hundreds in increasing order',
        timeStart: '03:00',
        timeEnd: '03:00',
        currentTime: 180,
      },
      {
        index: 5,
        text: 'Putting it all together',
        timeStart: '03:20',
        timeEnd: '03:20',
        currentTime: 200,
      },
    ],
  },
  Science: {
    1: [
      {
        id: 1,
        text: 'Lorem Ipsum',
        timeStamp: 0,
        timeStart: '0:00',
        timeEnd: '0:10',
        currentTime: 0,
      },
      {
        id: 2,
        text: 'Lorem Ipsum',
        timeStamp: 18000,
        timeStart: '0:10',
        timeEnd: '0:20',
        currentTime: 10,
      },
      {
        id: 3,
        text: 'Lorem Ipsum',
        timeStamp: 36000,
        timeStart: '0:20',
        timeEnd: '0:30',
        currentTime: 20,
      },
      {
        id: 4,
        text: 'Lorem Ipsum',
        timeStamp: 54000,
        timeStart: '0:30',
        timeEnd: '0:40',
        currentTime: 30,
      },
    ],
  },
  English: {
    1: [
      {
        index: 1,
        text: 'The 12 verb tenses.',
        timeStart: '00:00',
        timeEnd: '00:45',
        currentTime: 0,
      },
      {
        index: 2,
        text: 'Reason 1 for using simple present tense.',
        timeStart: '00:45',
        timeEnd: '01:25',
        currentTime: 45,
      },
      {
        index: 3,
        text: 'Reason 2 for using simple present tense',
        timeStart: '01:26',
        timeEnd: '02:30',
        currentTime: 86,
      },
      {
        index: 4,
        text: 'Negative Sentences',
        timeStart: '02:31',
        timeEnd: '03:07',
        currentTime: 151,
      },
      {
        index: 5,
        text: 'Questions',
        timeStart: '03:08',
        timeEnd: '03:45',
        currentTime: 188,
      },
      {
        index: 6,
        text: 'Comparison between Positive, Negative and ',
        timeStart: '03:46',
        timeEnd: '04:42',
        currentTime: 226,
      },
      {
        index: 7,
        text: 'Exercises in Simple Past Tense',
        timeStart: '04:43',
        timeEnd: '06:25',
        currentTime: 283,
      },
    ],
    2: [
      {
        index: 1,
        text: 'Reason 1 for using simple present tense.',
        timeStart: '00:00',
        timeEnd: '01:05',
        currentTime: 0,
      },
      {
        index: 2,
        text: 'Reason 2 for using simple present tense.',
        timeStart: '01:06',
        timeEnd: '02:14',
        currentTime: 66,
      },
      {
        index: 3,
        text: 'Reason 3 for using simple present tense.',
        timeStart: '02:15',
        timeEnd: '02:53',
        currentTime: 135,
      },
      {
        index: 4,
        text: 'Reason 4 for using simple present tense.',
        timeStart: '02:54',
        timeEnd: '03:40',
        currentTime: 174,
      },
    ],
    3: [],
    4: [
      {
        index: 1,
        text: 'The 12 verb tenses.',
        timeStart: '00:00',
        timeEnd: '00:34',
        currentTime: 0,
      },
      {
        index: 2,
        text: 'Positive Simple Past Statements',
        timeStart: '00:34',
        timeEnd: '01:22',
        currentTime: 34,
      },
      {
        index: 3,
        text: 'Negative Simple Past Statements',
        timeStart: '01:22',
        timeEnd: '02:04',
        currentTime: 82,
      },
      {
        index: 4,
        text: 'Questions in Simple Past Tense',
        timeStart: '02:04',
        timeEnd: '02:41',
        currentTime: 124,
      },
      {
        index: 5,
        text: 'Exercises in Simple Past Tense',
        timeStart: '02:41',
        timeEnd: '04:23',
        currentTime: 161,
      },
    ],
    5: [],
  },
};
