export const GET_ALL_PRODUCT_IDS_BULK_VIEW_REQUEST =
  'GET_ALL_PRODUCT_IDS_BULK_VIEW_REQUEST';
export const GET_ALL_PRODUCT_IDS_BULK_VIEW_SUCCESS =
  'GET_ALL_PRODUCT_IDS_BULK_VIEW_SUCCESS';
export const GET_ALL_PRODUCT_IDS_BULK_VIEW_FAILED =
  'GET_ALL_PRODUCT_IDS_BULK_VIEW_FAILED';

export const GET_TUTORS_BULK_VIEW_REQUEST = 'GET_TUTORS_BULK_VIEW_REQUEST';
export const GET_TUTORS_BULK_VIEW_SUCCESS = 'GET_TUTORS_BULK_VIEW_SUCCESS';
export const GET_TUTORS_BULK_VIEW_FAILED = 'GET_TUTORS_BULK_VIEW_FAILED';
export const LOAD_MORE_TUTORS_BULK_VIEW_SUCCESS =
  'LOAD_MORE_TUTORS_BULK_VIEW_SUCCESS';

export const GET_TOPICS_BULK_VIEW_REQUEST = 'GET_TOPICS_BULK_VIEW_REQUEST';
export const GET_TOPICS_BULK_VIEW_SUCCESS = 'GET_TOPICS_BULK_VIEW_SUCCESS';
export const GET_TOPICS_BULK_VIEW_FAILED = 'GET_TOPICS_BULK_VIEW_FAILED';
export const LOAD_MORE_TOPICS_BULK_VIEW_SUCCESS =
  'LOAD_MORE_TOPICS_BULK_VIEW_SUCCESS';

export const GET_CONTENT_BY_TOPICS_REQUEST = 'GET_CONTENT_BY_TOPICS_REQUEST';
export const GET_CONTENT_BY_TOPICS_SUCCESS = 'GET_CONTENT_BY_TOPICS_SUCCESS';
export const GET_CONTENT_BY_TOPICS_FAILED = 'GET_CONTENT_BY_TOPICS_FAILED';
export const LOAD_MORE_CONTENT_BULK_VIEW_SUCCESS =
  'LOAD_MORE_CONTENT_BULK_VIEW_SUCCESS';

export const GET_SUBJECT_BULK_VIEW_REQUEST = 'GET_SUBJECT_BULK_VIEW_REQUEST';
export const GET_SUBJECT_BULK_VIEW_SUCCESS = 'GET_SUBJECT_BULK_VIEW_SUCCESS';
export const GET_SUBJECT_BULK_VIEW_FAILED = 'GET_SUBJECT_BULK_VIEW_FAILED';

export const GET_CONTENT_BY_COUNT_REQUEST = 'GET_CONTENT_BY_COUNT_REQUEST';
export const GET_CONTENT_BY_COUNT_SUCCESS = 'GET_CONTENT_BY_COUNT_SUCCESS';
export const GET_CONTENT_BY_COUNT_FAILED = 'GET_CONTENT_BY_COUNT_FAILED';

export const SET_SELECTED_TUTOR_BULK = 'SET_SELECTED_TUTOR_BULK';
export const SET_TOGGLE_SELECT_ALL_BULK_TUTOR =
  'SET_TOGGLE_SELECT_ALL_BULK_TUTOR';
export const SET_EMPTY_LIKE_CONTENT_BULK_VIEW =
  'SET_EMPTY_LIKE_CONTENT_BULK_VIEW';
export const SUBMIT_BULK_VIEW_LIKE_REQUEST = 'SUBMIT_BULK_VIEW_LIKE_REQUEST';
export const SUBMIT_BULK_VIEW_LIKE_SUCCESS = 'SUBMIT_BULK_VIEW_LIKE_SUCCESS';
export const SUBMIT_BULK_VIEW_LIKE_FAIL = 'SUBMIT_BULK_VIEW_LIKE_FAIL';

export const BULK_VIEW_WATCH_LATER_IDS_REQUEST =
  'BULK_VIEW_WATCH_LATER_IDS_REQUEST';

export const BULK_VIEW_WATCH_LATER_IDS_FAILED =
  'BULK_VIEW_WATCH_LATER_IDS_FAILED';

export const RESET_BULK_VIEW_REDUCER = 'RESET_BULK_VIEW_REDUCER';

export const REMOVE_WATCH_LATER_VIDEO_BULK_VIEW_REQUEST =
  'REMOVE_WATCH_LATER_VIDEO_BULK_VIEW_REQUEST';
export const REMOVE_WATCH_LATER_VIDEO_BULK_VIEW_SUCCESS =
  'REMOVE_WATCH_LATER_VIDEO_BULK_VIEW_SUCCESS';
export const REMOVE_WATCH_LATER_VIDEO_BULK_VIEW_FAILED =
  'REMOVE_WATCH_LATER_VIDEO_BULK_VIEW_FAILED';

export const SUBMIT_WATCH_LATER_BULK_VIEW_REQUEST =
  'SUBMIT_WATCH_LATER_BULK_VIEW_REQUEST';
export const SUBMIT_WATCH_LATER_BULK_VIEW_SUCCESS =
  'SUBMIT_WATCH_LATER_BULK_VIEW_SUCCESS';
export const SUBMIT_WATCH_LATER_BULK_VIEW_FAILED =
  'SUBMIT_WATCH_LATER_BULK_VIEW_FAILED';
