export const COUNTRY_SELECTED = 'COUNTRY_SELECTED';
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED';
export const FILE_UPLOAD_REQUEST = 'FILE_UPLOAD_REQUEST';
export const FILE_UPLOAD_S3_INFO_FAILED = 'FILE_UPLOAD_S3_INFO_FAILED';
export const FILE_UPLOAD_S3_INFO_REQUEST = 'FILE_UPLOAD_S3_INFO_REQUEST';
export const FILE_UPLOAD_S3_INFO_SUCCESS = 'FILE_UPLOAD_S3_INFO_SUCCESS';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';

export const GET_ASSESSMENTS_FAILED = 'GET_ASSESSMENTS_FAILED';
export const GET_ASSESSMENTS_REQUEST = 'GET_ASSESSMENTS_REQUEST';
export const GET_ASSESSMENTS_SUCCESS = 'GET_ASSESSMENTS_SUCCESS';

export const GET_COUNTRIES_FAILED = 'GET_COUNTRIES_FAILED';
export const GET_COUNTRIES_REQUEST = 'GET_COUNTRIES_REQUEST';
export const GET_COUNTRIES_SUCCESS = 'GET_COUNTRIES_SUCCESS';
export const RESET_COUNTRIES = 'RESET_COUNTRIES';

export const GET_GRADES_FAILED = 'GET_GRADES_FAILED';
export const GET_GRADES_REQUEST = 'GET_GRADES_REQUEST';
export const GET_GRADES_SUCCESS = 'GET_GRADES_SUCCESS';
export const RESET_GRADES = 'RESET_GRADES';

export const GET_LESSONS_FAILED = 'GET_LESSONS_FAILED';
export const GET_LESSONS_REQUEST = 'GET_LESSONS_REQUEST';
export const GET_LESSONS_SUCCESS = 'GET_LESSONS_SUCCESS';
export const RESET_LESSONS = 'RESET_LESSONS';

export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
export const GET_ORDER_REQUEST = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS';
export const RESET_ORDER = 'RESET_ORDER';

export const GET_SCHOOLS_FAILED = 'GET_SCHOOLS_FAILED';
export const GET_SCHOOLS_REQUEST = 'GET_SCHOOLS_REQUEST';
export const GET_SCHOOLS_SUCCESS = 'GET_SCHOOLS_SUCCESS';
export const RESET_SCHOOLS = 'RESET_SCHOOLS';

export const GET_SUBJECTS_FAILED = 'GET_SUBJECTS_FAILED';
export const GET_SUBJECTS_REQUEST = 'GET_SUBJECTS_REQUEST';
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS';
export const RESET_SUBJECTS = 'RESET_SUBJECTS';

export const GET_SYLLABUSES_FAILED = 'GET_SYLLABUSES_FAILED';
export const GET_SYLLABUSES_REQUEST = 'GET_SYLLABUSES_REQUEST';
export const GET_SYLLABUSES_SUCCESS = 'GET_SYLLABUSES_SUCCESS';
export const RESET_SYLLABUSES = 'RESET_SYLLABUSES';

export const GET_TOPICS_FAILED = 'GET_TOPICS_FAILED';
export const GET_TOPICS_REQUEST = 'GET_TOPICS_REQUEST';
export const GET_TOPICS_SUCCESS = 'GET_TOPICS_SUCCESS';
export const RESET_TOPICS = 'RESET_TOPICS';

export const GET_TUTORS_FAILED = 'GET_TUTORS_FAILED';
export const GET_TUTORS_REQUEST = 'GET_TUTORS_REQUEST';
export const GET_TUTORS_SUCCESS = 'GET_TUTORS_SUCCESS';
export const RESET_TUTORS = 'RESET_TUTORS';
export const RESET_ASSESMENTS = 'RESET_ASSESMENTS';

export const GET_USEREXIST_FAILED = 'GET_USEREXIST_FAILED';
export const GET_USEREXIST_REQUEST = 'GET_USEREXIST_REQUEST';
export const GET_USEREXIST_SUCCESS = 'GET_USEREXIST_SUCCESS';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_SELECTED_GRADE = 'SET_SELECTED_GRADE';
export const SET_SELECTED_SCHOOL = 'SET_SELECTED_SCHOOL';
export const SET_SELECTED_SUBJECT = 'SET_SELECTED_SUBJECT';
export const SET_SELECTED_SYLLABUS = 'SET_SELECTED_SYLLABUS';
export const SET_SELECTED_TOPIC = 'SET_SELECTED_TOPIC';
export const SET_SELECTED_TUTOR = 'SET_SELECTED_TUTOR';
export const VIEW_DOCUMENT_UPLOAD_REQUEST = 'VIEW_DOCUMENT_UPLOAD_REQUEST';
export const VIEW_DOCUMENT_UPLOAD_SUCCESS = 'VIEW_DOCUMENT_UPLOAD_SUCCESS';
export const VIEW_DOCUMENT_UPLOAD_FAILED = 'VIEW_DOCUMENT_UPLOAD_FAILED';
export const RESET_USEREXIST_FETCH = 'RESET_USEREXIST_FETCH';

export const INTERVIEW_UPLOAD_FAILED = 'INTERVIEW_UPLOAD_FAILED';
export const INTERVIEW_UPLOAD_REQUEST = 'INTERVIEW_UPLOAD_REQUEST';
export const INTERVIEW_UPLOAD_SUCCESS = 'INTERVIEW_UPLOAD_SUCCESS';

export const GET_RELATED_DOCUMENT_CONTENTS_FAILED =
  'GET_RELATED_DOCUMENT_CONTENTS_FAILED';
export const GET_RELATED_DOCUMENT_CONTENTS_REQUEST =
  'GET_RELATED_DOCUMENT_CONTENTS_REQUEST';
export const GET_RELATED_DOCUMENT_CONTENTS_SUCCESS =
  'GET_RELATED_DOCUMENT_CONTENTS_SUCCESS';
export const RESET_RELATED_DOCUMENT_CONTENTS =
  'RESET_RELATED_DOCUMENT_CONTENTS';

export const GET_RELATED_VIDEO_CONTENTS_FAILED =
  'GET_RELATED_VIDEO_CONTENTS_FAILED';
export const GET_RELATED_VIDEO_CONTENTS_REQUEST =
  'GET_RELATED_VIDEO_CONTENTS_REQUEST';
export const GET_RELATED_VIDEO_CONTENTS_SUCCESS =
  'GET_RELATED_VIDEO_CONTENTS_SUCCESS';
export const RESET_RELATED_VIDEO_CONTENTS = 'RESET_RELATED_VIDEO_CONTENTS';

export const GET_RELATED_ASSIGNMENT_CONTENTS_FAILED =
  'GET_RELATED_ASSIGNMENT_CONTENTS_FAILED';
export const GET_RELATED_ASSIGNMENT_CONTENTS_REQUEST =
  'GET_RELATED_ASSIGNMENT_CONTENTS_REQUEST';
export const GET_RELATED_ASSIGNMENT_CONTENTS_SUCCESS =
  'GET_RELATED_ASSIGNMENT_CONTENTS_SUCCESS';
export const RESET_RELATED_ASSIGNMENT_CONTENTS =
  'RESET_RELATED_ASSIGNMENT_CONTENTS';

export const GET_CURRENCY_FAILED = 'GET_CURRENCY_FAILED';
export const GET_CURRENCY_REQUEST = 'GET_CURRENCY_REQUEST';
export const GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS';
export const RESET_CURRENCY = 'RESET_CURRENCY';
export const RESET_USEREXIST = 'RESET_USEREXIST';

export const GET_ALL_SUBSCRIPTION_REQUEST = 'GET_ALL_SUBSCRIPTION_REQUEST';
export const GET_ALL_SUBSCRIPTION_SUCCESS = 'GET_ALL_SUBSCRIPTION_SUCCESS';
export const GET_ALL_SUBSCRIPTION_FAILED = 'GET_ALL_SUBSCRIPTION_FAILED';

export const GET_TOTAL_RECORDS_REQUEST = 'GET_TOTAL_RECORDS_REQUEST';
export const GET_TOTAL_RECORDS_SUCCESS = 'GET_TOTAL_RECORDS_SUCCESS';
export const GET_TOTAL_RECORDS_FAILED = 'GET_TOTAL_RECORDS_FAILED';

export const GET_ALL_SUBSCRIPTION_FEATURE_REQUEST =
  'GET_ALL_SUBSCRIPTION_FEATURE_REQUEST';
export const GET_ALL_SUBSCRIPTION_FEATURE_SUCCESS =
  'GET_ALL_SUBSCRIPTION_FEATURE_SUCCESS';
export const GET_ALL_SUBSCRIPTION_FEATURE_FAILED =
  'GET_ALL_SUBSCRIPTION_FEATURE_FAILED';
export const RESET_SUBSCRIPTION_FEATURE = 'RESET_SUBSCRIPTION_FEATURE';

export const LIST_DATA_REQUEST = 'LIST_DATA_REQUEST';
export const LIST_DATA_SUCCESS = 'LIST_DATA_SUCCESS';
export const LIST_DATA_FAILED = 'LIST_DATA_FAILED';

export const INITIAL_DATA_LIST_SETUP = 'INITIAL_DATA_LIST_SETUP';

export const GET_ALL_WATCH_LATER_IDS_REQUEST =
  'GET_ALL_WATCH_LATER_IDS_REQUEST';
export const GET_ALL_WATCH_LATER_IDS_SUCCESS =
  'GET_ALL_WATCH_LATER_IDS_SUCCESS';
export const GET_ALL_WATCH_LATER_IDS_FAILED = 'GET_ALL_WATCH_LATER_IDS_FAILED';

export const GET_ALL_LIKE_VIDEO_DATA_REQUEST =
  'GET_ALL_LIKE_VIDEO_DATA_REQUEST';
export const GET_ALL_LIKE_VIDEO_DATA_SUCCESS =
  'GET_ALL_LIKE_VIDEO_DATA_SUCCESS';
export const GET_ALL_LIKE_VIDEO_DATA_FAIL = 'GET_ALL_LIKE_VIDEO_DATA_FAIL';

export const SET_EMPTY_ALL_LIKED_CONTENT = 'SET_EMPTY_ALL_LIKED_CONTENT';

export const GET_WATCH_LATER_IDS_TOTAL_RECORDS =
  'GET_WATCH_LATER_IDS_TOTAL_RECORDS';

export const USER_LAST_WATCHED_VIDEO_CONTENT_REQUEST =
  'USER_LAST_WATCHED_VIDEO_CONTENT_REQUEST';
export const USER_LAST_WATCHED_VIDEO_CONTENT_SUCCESS =
  'USER_LAST_WATCHED_VIDEO_CONTENT_SUCCESS';
export const USER_LAST_WATCHED_VIDEO_CONTENT_FAILED =
  'USER_LAST_WATCHED_VIDEO_CONTENT_FAILED';

export const USER_LAST_WATCH_VIDEO_TIMESTAMP_REQUEST =
  'USER_LAST_WATCH_VIDEO_TIMESTAMP_REQUEST';
export const USER_LAST_WATCH_VIDEO_TIMESTAMP_SUCCESS =
  'USER_LAST_WATCH_VIDEO_TIMESTAMP_SUCCESS';
export const USER_LAST_WATCH_VIDEO_TIMESTAMP_FAILED =
  'USER_LAST_WATCH_VIDEO_TIMESTAMP_FAILED';

export const GET_LEARNING_DOCUMENTS_REQUEST = 'GET_LEARNING_DOCUMENTS_REQUEST';
export const GET_LEARNING_DOCUMENTS_SUCCESS = 'GET_LEARNING_DOCUMENTS_SUCCESS';
export const GET_LEARNING_DOCUMENTS_FAIL = 'GET_LEARNING_DOCUMENTS_FAIL';

export const GET_LEARNING_LINKED_DOCUMENTS_REQUEST =
  'GET_LEARNING_LINKED_DOCUMENTS_REQUEST';
export const GET_LEARNING_LINKED_DOCUMENTS_SUCCESS =
  'GET_LEARNING_LINKED_DOCUMENTS_SUCCESS';
export const GET_LEARNING_LINKED_DOCUMENTS_FAIL =
  'GET_LEARNING_LINKED_DOCUMENTS_FAIL';

export const RESET_LEARNING_DOCUMENTS = 'RESET_LEARNING_DOCUMENTS';
